# Generated by Django 5.2.3 on 2025-06-21 08:16

import MLS.models
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLS', '0002_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_name', models.CharField(max_length=200)),
                ('zpid', models.CharField(default=MLS.models.default_zpid, max_length=200)),
                ('price', models.FloatField(db_index=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('type', models.CharField(db_index=True, max_length=50)),
                ('space', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('bedrooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('bathrooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('county', models.CharField(max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('streetAddress', models.CharField(max_length=200)),
                ('status', models.CharField(default='available', max_length=200)),
                ('views', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('images', models.ImageField(blank=True, null=True, upload_to='listing_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('MLS.user',),
            managers=[
                ('seller', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(18)]),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='buyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.IntegerField(blank=True, null=True)),
                ('budget', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('address', models.CharField(max_length=200)),
                ('P_price', models.FloatField(default=0.4, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('P_square_feet', models.FloatField(default=0.4, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('P_bedrooms', models.FloatField(default=0.4, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('P_bathrooms', models.FloatField(default=0.4, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('P_year', models.FloatField(default=0.4, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('saved_listings', models.ManyToManyField(blank=True, null=True, to='MLS.listing')),
            ],
        ),
        migrations.CreateModel(
            name='sellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.IntegerField(blank=True, null=True)),
                ('company', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='seller_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MLS.seller'),
        ),
    ]
