# Generated by Django 5.2.3 on 2025-06-21 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLS', '0003_listing_seller_user_age_buyerprofile_sellerprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='seller_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MLS.sellerprofile'),
        ),
    ]
