# Generated by Django 5.2.3 on 2025-06-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MLS', '0004_alter_listing_seller_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerprofile',
            name='buyer_id',
        ),
    ]
