# Generated by Django 5.2.3 on 2025-06-21 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLS', '0005_remove_buyerprofile_buyer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, default=18, validators=[django.core.validators.MinValueValidator(18)]),
        ),
    ]
