# Generated by Django 5.2.3 on 2025-06-22 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLS', '0006_alter_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='seller_id',
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='budget',
            field=models.FloatField(default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
