# Generated by Django 5.2.3 on 2025-06-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLS', '0008_alter_buyerprofile_saved_listings_chats_chatlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
